server:
  port: 2005

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/auth/**,/users/**,/api/users/**

        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/api/tasks/**,/tasks/**

        - id: submission-service
          uri: lb://submission-service
          predicates:
            - Path=/api/submissions/**,/submissions/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: false 

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
