server:
  port: 2054


spring:
  application:
    name: TASK_SERVICE

  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/task_service
    username: root
    password: Qu@ngminh80
    driver-class-name: com.mysql.cj.jdbc.Driver



