server:
  port: 2056

spring:
  application:
    name: TASK_SERVICE

  datasource:
    url: jdbc:mysql://localhost:3307/pdm_project
    username: root
    password: Qu@ngminh80
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
