server:
  port: 2005

spring:
  application:
    name: GATEWAY-SERVICE

  spring:
    cloud:
      gateway:
        mvc:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          routes:
            - id: USER_SERVICE
              uri: lb://USER_SERVICE
              predicates:
                - Path=/auth/**,/users/**,/api/users/**

            - id: TASK_SERVICE
              uri: lb://TASK_SERVICE
              predicates:
                - Path=/api/tasks/**,/tasks/**

            - id: SUBMISSION_SERVICE
              uri: lb://SUBMISSION_SERVICE
              predicates:
                - Path=/api/submissions/**,/submissions/**
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins: "*"
                allowed-methods: "*"
                allowed-headers: "*"
        globalcors:
          cors-configurations:
            '[/**]':
              allowed-origins: "*"
              allowed-methods: "*"
              allowed-headers: "*"

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
