server:
  port: 2005

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      mvc:
        routes:
          - id: USER_SERVICE
            uri: lb://USER_SERVICE  # Chú ý: Đảm bảo tên service chính xác như đã đăng ký trên Eureka
            predicates:
              - Path=/auth/**,/users/**,/api/users/**

          - id: TASK_SERVICE
            uri: lb://TASK_SERVICE  # Chú ý: Đảm bảo tên service chính xác như đã đăng ký trên Eureka
            predicates:
              - Path=/api/tasks/**,/tasks/**

          - id: SUBMISSION_SERVICE
            uri: lb://SUBMISSION_SERVICE  # Chú ý: Đảm bảo tên service chính xác như đã đăng ký trên Eureka
            predicates:
              - Path=/api/submissions/**,/submissions/**
      httpclient:
        connect-timeout: 3000
        response-timeout: 10s

  # Cấu hình CORS riêng biệt cho Spring MVC
  mvc:
    cors:
      mapping: /**
      allowed-origins: "*"
      allowed-methods: GET, POST, PUT, DELETE, PATCH
      allowed-headers: "*"
      allow-credentials: true

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    com.PDM.gateway: DEBUG