server:
  port: 2055

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3307/pdm_project
    username: root
    password: Qu@ngminh80
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/


